### ISSUE TITLE
Cassette support

### ISSUE THREAD

**Issue by sh95014** [sh95014/AppleWin#16]
**Describe the bug**
Parity with AppleWin.

**Comment by audetto** [comment]
Hi,

I added cassette support for `.wav` files from https://asciiexpress.net

https://github.com/audetto/AppleWin/blob/master/source/linux/tape.cpp#L37-L57

I wanted to add ability to listen to a real (SDL) source, for which I suspect that the threshold would make some difference, but never had time or enough will to do it.
