### ISSUE TITLE
I'm unable to pick a dsk file to load, built from source on macOS Catalina x86 64 bit

### ISSUE THREAD

**Issue by rrcook** [sh95014/AppleWin#24]
**Describe the bug**
In the "system" dialog, picking disks, there's no way to choose files to load for disks.

**To Reproduce**
1. [Go to '...'](https://github.com/sh95014/AppleWin/releases/tag/Mariani-1.0-1)
2. Download the zip file
3. Read the instructions in macOS.md, follow the instructions including git clone, brew install, etc. Build the application, macOS Catalina, x86 64-bit.
4. Run it, open the system dialog, go to the disks tab. Try clicking in the Filename area, no way to open to select a file.

**Expected behavior**
Expected to have a file open dialog or something similar.

**Actual behavior**
No file open dialog, no way to type in a filename.

**Screenshots**

**Versions (please complete the following information):**
 - OS: macOS Catalina 10.15.7
 - Mariani: [e.g. git hash]

**Additional context**

**Comment by sh95014** [comment]
Hi! Thanks for the report, and I'm sorry I didn't see this until just now. I need to figure out how to get alerted properly...

To clarify, are you trying the File > Insert Disk Image menu item, or the round disk buttons in the status bar at the bottom of the window?

Either way, the open dialog is restricted to the following file extensions for disk images. What disk images were you trying to open?

```
    NSArray *supportedTypes = @[ @"BIN", @"DO", @"DSK", @"NIB", @"PO", @"WOZ", @"ZIP", @"GZIP", @"GZ" ];
```

**Comment by rrcook** [comment]
I don't see anything like that. The "apple" menu at the top only has "sa2"
and "Window", and the menu inside the application has a "System" menu. It
brings up a tabbed dialog, and for Disks there's no way to tap where it
says "Filename". Below is a screenshot.
[image: Screen Shot 2022-06-25 at 10.34.40 PM.png]

**Comment by sh95014** [comment]
Oh, you're running `sa2`. That's not really a Mac app, it's pretty much just building the Linux/SDL2 port. Just drag and drop the disk image into the main window, and it'll be "inserted" into one of the drives.

You can see what's inserted by going to System > Settings > Disks. Note that there's another menu bar inside the app's window:

<img width="825" alt="Screen Shot 2022-06-25 at 10 35 15 PM" src="https://user-images.githubusercontent.com/95387068/175801028-e2977138-8161-448d-ae22-346f44699869.png">

What I've built is a proper Mac app that you can download at https://github.com/sh95014/AppleWin/releases/tag/Mariani-1.0-1 or of course build from source if you like. See https://github.com/sh95014/AppleWin/blob/master/macOS.md for details.

**Comment by sh95014** [comment]
@rrcook Did that resolve your issue?

**Comment by sh95014** [comment]
No response from originator, closing.
