### ISSUE TITLE
Feature requests: option to display ASCII with bit 7 set in hex viewer; and option for all-ASCII (no bytes) view

### ISSUE THREAD

**Issue by IvanExpert** [sh95014/AppleWin#46]
**Describe the bug**
When using the disk file browser, if you open a DOS 3.3 text file, the high bit is likely to be set, making the contents appear as periods in a hex dump. The high bit is set on text in lots of other contexts as well, especially in the pre-ProDOS days, such as  indicating a string termination on the final character.

**To Reproduce**
1. Insert the DOS 3.3 System Master
2. Click Examine...
3. Double-click APPLE PROMS

**Expected behavior**
It does what you'd expect, but I'd like an option to be able to display the text as though the high bit weren't set, so that the ASCII characters would be revealed. I'd also like an option to hide the bytes, so you can just read a text file.

**Actual behavior**
None of the ASCII text in the file is visible because the high bit is set on all characters.

**Screenshots**
Screenshot attached.

**Versions (please complete the following information):**
 - OS: macOS 15.1.1
 - Mariani: 1.4 (3)
 
<img width="437" alt="Screenshot 2024-12-01 at 3 15 45 PM" src="https://github.com/user-attachments/assets/e888a07f-8997-49ca-b342-c3813bcc29c4">

**Comment by sh95014** [comment]
Getting HexFiend to understand Apple ][ text encoding would be a somewhat deep change, and I don't imagine they'll be too interested in it upstream. So just gonna do that for Mariani:

https://github.com/sh95014/HexFiend/commit/88426111d171d397d23803ef60a00ce8467cd6f1
https://github.com/sh95014/AppleWin/commit/7df0d1281df81fe5fd6e43f5a9305f81b3b1b72c

**Comment by sh95014** [comment]
added a button to the window title bar to toggle the hex view:

<img width="611" alt="截圖 2024-12-29 下午1 23 41" src="https://github.com/user-attachments/assets/269bf4a4-4fdf-49a3-a70b-209db6c6887d" />
