### ISSUE TITLE
PR#6 does not completely reset the machine state

### ISSUE THREAD

**Issue by callapple** [sh95014/AppleWin#50]
**Describe the bug**
PR#6 in DOS 3.3 does not reset the machine start and perform a startup, with the Apple //e at the top of the screen

**To Reproduce**
1. Boot DOS
2. do a PR#6

**Expected behavior**
Machine state should clear screen, place Apple //e at top of screen and boot current floppy / HDD

**Actual behavior**
Just boots disk and places user in a continuation of DOS further down the screen

**Screenshots**
![Screenshot 2024-12-29 at 10 06 32](https://github.com/user-attachments/assets/a720e542-2297-4eac-9a8d-cb8518c590d5)

**Versions (please complete the following information):**
 - OS: [e.g. macOS 12.2.1]
 - Mariani: [e.g. git hash]

**Additional context**

**Comment by sh95014** [comment]
This also happens in sa2 so it's probably an upstream issue. Will verify with AppleWin on Windows and forward the report along.

**Comment by sh95014** [comment]
Closing in favor of https://github.com/AppleWin/AppleWin/issues/1354
